### ISSUE TITLE
Module 4 - Lab 3 - Exercise 3 - ImportCsvToSharepointList.ps1 file has wrong path

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#31] opened 2021-01-19 00:16 UTC
# Module: 04
#### Step: 34

Description of issue
**ImportCsvToSharepointList.ps1** file has wrong local path in line 21.

The path indicates this:

![image](https://user-images.githubusercontent.com/49700217/104972930-0fd61c00-59a8-11eb-887f-0e372830e7e4.png)

...but actual path is going to be C:\Users\Administrator.Adatum\Documents\Service Request System.csv

Would it be possible to attach corrected versions of the files to this GH repo for easy-downloading of corrected files?  (this could also be added to the instructions to be modified, but it seems best to have any individual files added to repo in case of any other issues now or in future)

**Comment by tfrink** [comment] 2021-01-27 19:50
We are unable to reproduce this error. It appears you may be using an outdated version of the import script file. I have attached a screen shot of the current MS-100 VM from Microsoft's lab hosting provider that shows the script file open. Note the path is on line 4 rather than line 21, and it references the Administrator folder rather than the DomainAdmin folder in the path. I have also attached a screen shot showing the File Explorer window for the Administrator account, and it displays the csv file.

![csv file screen shot](https://user-images.githubusercontent.com/12913870/106045336-69c09b00-60a6-11eb-8e96-ff2f87149dbd.png)
![Import Script screen shot](https://user-images.githubusercontent.com/12913870/106045338-6a593180-60a6-11eb-9504-10fbbc6485b0.png)

**Comment by tfrink** [comment] 2021-01-27 20:08
Please ignore my prior comment. In the prior course release, the files for this exercise were stored under the Administrator account. When I went to File Explorer and looked under the C:Users\Administrator\Documents folder, I found the files and assumed they were the ones. However, I just discovered that the files are in the Administrator.Adatum folder as you mentioned. These are the latest and greatest files, and Yes, I confirmed the bug you reported on the folder path in line 21. We will get this fixed in the VM.

My apologies for the confusion. As for storing the files in GitHub, I'll have to check with management to see if this is something we can do.

**Comment by tfrink** [comment] 2021-01-27 23:56
With regard to attaching the VM-related files into the GitHub repo, I was informed that because the files are proprietary to Microsoft, we could not make them available publicly in this manner. That being said, I want to thank you again for all your help in notifying us of the issues that you ran into. Your efforts are very much appreciated!

**Closed by tfrink** 2021-01-27 23:56 UTC

**Comment by TesterTesterson1004** [comment] 2021-01-28 01:34
Isn't this precisely what the 'Allfiles' dir in the repo is for?   

https://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services/tree/master/Allfiles

It has versions already present from the older/obsolete revision of the course,  which could be updated.  And nearly all other MicrosoftLearning MOC courses that have any sort of \Allfiles in a VM - whether that is code, VS projects, .ps1 scripts, .docx's, or etc., make use of public Allfiles components in their repos to map to <drive>:\Labfiles dirs on the VMs.

It is ridiculously useful to distribute updates to VM <drive>:\Labfiles dirs that way, rather then try and update & then re-release a whole new set of VMs when the changes only amount to items that could otherwise be delivered via a download/clone from a Github \AllFiles dir.   

Just saying... :)
